---
title: "Análise de Cancelamento de Assinaturas"
author: "Caroline Vasconcelos"
format: pdf
editor: visual
---

## 

Buscando mitigar o número de cancelamentos de pacotes de uma empresa de streaming, a empresa em questão buscou dentro do seu próprio banco de dados, soluções para lidar com esse problema.

Usou-se a linguagem **phyton** para **minerar, modelar e visualizar** os dados. Feitas as devidas observações com relação a variável de cancelamento, chegou-se as seguintes conclusões:

-   A taxa de cancelamento global é de 56,7%. Isso indica que mais da metade dos clientes cancelaram seus contratos.

-   Contratos mensais têm uma taxa de cancelamento **média** de 100%, enquanto contratos anuais e quadrimestrais têm taxas médias de 46%. Isso sugere que os contratos mensais são mais propensos a serem cancelados em comparação com os contratos anuais e quadrimestrais.

-   A média de ligações para o Call Center é mais alta em contratos mensais (4,98), indicando uma possível correlação entre a necessidade de suporte e a decisão de cancelar.

-   O número médio de dias de atraso no pagamento é mais alto para contratos mensais (15 dias), o que pode contribuir para a alta taxa de cancelamento nesse grupo.

-   Após a remoção dos contratos mensais, a taxa de cancelamento geral cai para 46,1%. Isso destaca a influência significativa dos contratos mensais na taxa global de cancelamento.

-   A distribuição das assinaturas mostra que a Standard é ligeiramente mais frequente, seguida por Premium e Basic.

-   A análise revela que a Basic tem a maior taxa de cancelamento (47,5%), enquanto Standard e Premium têm taxas mais baixas (45,5% e 45,2%, respectivamente).

        
\begin{center}
Considerações Finais
\end{center}

-   A remoção dos contratos mensais teve um impacto positivo na redução da taxa de cancelamento.

-   Fatores-chave associados ao cancelamento incluem contratos mensais, necessidade de ligações no Call Center e atrasos no pagamento.

-   Estratégias para aplacar esses fatores podem contribuir para a redução adicional da taxa de cancelamento.

Ao abordar essas questões específicas, é possível tomar medidas mais direcionadas para melhorar a retenção de clientes e otimizar as estratégias de contrato e atendimento ao cliente.
